### ISSUE TITLE
No Windows Build Instructions

### ISSUE THREAD

**Issue by Mikumiku747** [renpy/pygame_sdl2#14] opened 2015-08-14 14:18 UTC
There currently aren't any Windows build instructions, and I'm trying to compile in cygwin as I write this, so would you like me to add a little part to the README on windows installation once I get it working?

**Comment by IronManMark20** [comment] 2015-09-08 16:27
I got the setup.py to run without failing looking for libs, but it isn't finding the include dir I point to. I am building for MS visual  c though, so I am not sure about cygwin.

**Comment by renpytom** [comment] 2015-09-08 22:32
How are you pointing it to include directories?

I just modified the code so that it's now possible to set the PYGAME_SDL2_CFLAGS and PYGAME_SDL2_LDFLAGS variables. These are in a GCC-style format, but it should be possible to use them on windows:

CFLAGS:
- Arguments beginning with -I are treated as include directories.
- Other arguments are treated as extra compile arguments.

LDFLAGS:
- Arguments beginning with -L are treated as library directories.
- Arguments beginning with -l are treated as libraries.
- Other arguments are treated as extra compile arguments.

**Comment by IronManMark20** [comment] 2015-09-08 23:30
I was manually appending the path to the include directory of the sdl2 source to `include_dirs` and extra compile args to `extra_compile_args`. I may have made a mistake in doing so. I have 2 questions:

1. Does this project support Python 3? (I am compiling with VS 2010, and testing the setup.py with Python 3. I have so far assumed it does, because I did not see a Python 2 only notice, but if so, I need to change compiler versions.)

2. I do not see any .lib files in the SDL sources. Any idea what I should be pointing to?

Also, if the aforementioned environment variables aren't set, it will give a file not found. I will make a PR to add exception checking when I get stuff working.

**Comment by renpytom** [comment] 2015-09-09 05:55
I don't know how to build SDL with MSVC. I think it's possible, and that the SDL sources have some sort of "solution file."

**Comment by IronManMark20** [comment] 2015-09-09 13:40
I can build the sources from the solution file, but not from the setup.py. when I build  it I get a dll and a bunch of .obj files (object files).

**Comment by IronManMark20** [comment] 2015-09-12 19:58
Well, it finds all the SDL headers now. The problem is that it is looking for stdint.h, which isn't included in Windows, of course.

**Comment by kne** [comment] 2015-12-12 23:23
@IronManMark20 Did you manage to get this going? I started building conda packages of pygame_sdl2 for Linux and OS X which seem to work well, but I'm not having much luck on Windows.

For reference, my prebuilt packages: https://anaconda.org/kne/pygame_sdl2/files
And the conda recipe: https://github.com/kne/conda-recipes/tree/master/pygame_sdl2/dev

**Comment by IronManMark20** [comment] 2015-12-13 00:55
@kne , no I had no success, unfortunately, I will try again, because honestly I've forgotten what stopped me. If your interested, maybe we can work out the problems together.

**Comment by renpytom** [comment] 2015-12-13 01:16
At least from my perspective, the problem isn't so much building on windows - I do that nightly for Ren'Py. It's figuring out how to place the SDL2 DLLs in the right place so Python can find them.

**Comment by IronManMark20** [comment] 2015-12-13 01:17
Ah, I see. Could you provide an explanation of how you have it set up?

**Comment by renpytom** [comment] 2015-12-13 01:52
It's pretty easy to get things compiled - I use gcc on windows to compile all the dependencies, then SDL2, then pygame. For Ren'Py, I then use a packaging script to build a python distribution that has all the files in the right place - but that's not a general solution.

**Comment by kne** [comment] 2015-12-13 14:24
If we're being honest, I think, 'easy' is when you can rely on a package manager for all the dependencies and not have to manage and compile them yourself. Unfortunately, we don't get that with Windows.

@renpytom Would you be able to at least list the dependencies and their version numbers you use for SDL2? Once I get it going with my conda recipe, I can put together some build instructions. I don't think the DLL location should be an issue for conda, at least.

**Comment by renpytom** [comment] 2015-12-14 05:29
I spent today getting a way to build pygame_sdl2 on windows set up. It should now be possible to build by cloning renpy/pygame_sdl2, by cloning renpy/pygame_sdl2_windeps into it (so the directory pygame_sdl2/pygame_sdl2_windeps exists), and then simply doing:

python setup.py build

So far, I've only tried getting this working with 32-bit Python 3.5 on Windows 10, using Visual Studio 2015. I'd appreciate feedback from anyone who gets this working or fails. 

Python 2.7 should work as well, but I'm getting an error about a missing vcvarsall.bat that is preventing me from building any Python binary there using MSVC. (I suspect it's an easy fix, but I need to call it a night.)

**Comment by kne** [comment] 2015-12-14 12:45
@renpytom - great! Thanks for spending the time to put that together. I'll try to get you some feedback soon.

As far as Visual Studio goes, from what I've read (and personal experience poking around getting the other packages to build) you need VS 2008 for Python 2.7 and VS 2010 for Python 3.x (the ABI changed significantly between those versions and as such they're incompatible). In addition to that, you need the Windows SDK for each to get the respective x64 compilers. `vcvarsall` then has a bug in which it looks for the wrong amd64 batch file and it needs modification for both versions. It's a _really_ ugly process altogether...

**Comment by IronManMark20** [comment] 2015-12-14 15:46
@renpytom that rocks! I think the only major issue for 2.7 is that if you build for VC9 (Visual Studio 2008) it is missing stdint.h, but 2010 and higher have it. The solution for your missing vcvarsall is to install the Python tools for VS 2008.[here](https://www.microsoft.com/en-us/download/details.aspx?id=44266).

**Comment by Thraka** [comment] 2016-01-13 18:04
Anyone have a windows build for download? I hate having to install tons of dependencies just to build a file :sob: Thanks!

**Comment by renpytom** [comment] 2016-01-13 22:39
What python are you running? I have some experimental wheels building.

**Comment by Thraka** [comment] 2016-01-14 01:34
The latest from the website

**Comment by renpytom** [comment] 2016-01-14 01:35
32 or 64-bit?

**Comment by IronManMark20** [comment] 2016-01-14 01:48
@renpytom while you are at it, could you do Python 2.7 32bit? I would greatly appreciate it!

**Comment by Thraka** [comment] 2016-01-14 02:10
32 right now, any real reason to run 64?

**Comment by IronManMark20** [comment] 2016-01-14 02:30
@Thraka I know some people do so for eg, C extensions. If I have a library that is x86-64, then Python should be too. Some Python programs have very high memory usage, so people use it for that too.

**Comment by Thraka** [comment] 2016-01-14 05:50
@IronManMark20 Sure I can see that on data analysis and number crunching, but not for gaming :) But who knows I may be wrong :P

**Comment by renpytom** [comment] 2016-01-24 19:11
We are now producing nightly builds of pygame_sdl2 at:

http://nightly.renpy.org/pygame_sdl2/

This includes wheels for 32- and 64-bit versions of Python 2.7 and Python 3.5. I've also added windows build instructions to the README file.  So I think I can, finally, close this bug. 

Please let me know if this works out for everyone.

**Closed by renpytom** 2016-01-24 19:11 UTC

**Comment by IronManMark20** [comment] 2016-01-24 21:47
Thanks so much @renpytom, that looks great! Downloading now.
